# Generated by Django 5.0.3 on 2024-03-13 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="user",
        ),
    ]
