# Generated by Django 5.0.3 on 2024-03-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0001_initial"),
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendar",
            name="contacts",
            field=models.ManyToManyField(
                blank=True, related_name="calendars", to="contacts.contact"
            ),
        ),
    ]
