# Generated by Django 5.0.3 on 2024-03-13 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0002_calendar_contacts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calendar",
            name="owner",
        ),
    ]
